import FPLogin from "../../fixtures/fixturesFP/FPLogin.json"
import LoginClass from "../../support/supportFP/s01Login.js"
import Dashboard from "../../support/supportFP/s03Attendance.js"
import f03Dahsboard from "../../fixtures/fixturesFP/f03Dashboard.json"
const loginPage = new LoginClass()
const dashboard = new Dashboard()

describe('Submit Attendance pada Time At Work', () => {
    it('Pengguna memasukkan valid date dan valid time', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        dashboard.interceptTimeAtWork()
        dashboard.clickTimeAtWork()
        dashboard.waitTimeAtWork()
        dashboard.interceptIn()
        dashboard.clickIn()
        dashboard.waitIn()
        dashboard.assertionPunch()
    })
    it('Pengguna memasukkan valid date dan valid time serta notes', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        dashboard.interceptTimeAtWork()
        dashboard.clickTimeAtWork()
        dashboard.waitTimeAtWork()
        dashboard.assertionAttendance()
        dashboard.inputNotes(f03Dahsboard.baseNotes)
        dashboard.interceptIn()
        dashboard.clickIn()
        dashboard.waitIn()
        dashboard.assertionPunch()
    })
    it('Pengguna memasukkan valid date dan valid time dengan notes panjang', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        dashboard.interceptTimeAtWork()
        dashboard.clickTimeAtWork()
        dashboard.waitTimeAtWork()
        dashboard.assertionAttendance()
        dashboard.inputNotes(f03Dahsboard.longNotes)
        dashboard.clickIn()
        dashboard.assertionLongNotes()
    })
    it('Pengguna memasukkan valid date dan valid time serta invalid characters pada notes', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        dashboard.interceptTimeAtWork()
        dashboard.clickTimeAtWork()
        dashboard.waitTimeAtWork()
        dashboard.assertionAttendance()
        dashboard.inputNotes(f03Dahsboard.invalidNotes)
        dashboard.interceptIn()
        dashboard.clickIn()
        dashboard.waitIn()
        dashboard.assertionPunch()
    }) 
    it('Pengguna memasukkan date kosong dan valid time', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        dashboard.interceptTimeAtWork()
        dashboard.clickTimeAtWork()
        dashboard.waitTimeAtWork()
        dashboard.clearCalender()
        dashboard.clickIn()
        dashboard.assertionUnsuccesPunchIn()
    })
})