import FPLogin from "../../fixtures/fixturesFP/FPLogin.json"
import LoginClass from "../../support/supportFP/s01Login.js"
import TopBar from "../../support/supportFP/s04TopBar.js"
import f04TopBar from "../../fixtures/fixturesFP/f04TopBar.json"
const loginPage = new LoginClass()
const topbar = new TopBar()

describe('Verifikasi fitur pada top bar', () => {
    it('Pengguna dapat mengakses fitur About', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        topbar.clickProfile()
        topbar.clickAbout()
        topbar.assertionAbout()
    })
    it('Pengguna dapat mengakses fitur Support', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        topbar.clickProfile()
        topbar.clickSupport()
        topbar.assertionSupport()
    })
    it('Pengguna melakukan Change Password dengan valid password', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        topbar.clickProfile()
        topbar.clickChangePSW()
        topbar.assertionChangePSW()
        topbar.inputValidData(FPLogin.validPSW, f04TopBar.newValidPSW)
        topbar.clickSave()
        topbar.assertionSavePSW()
    })
    it('Pengguna melakukan Change Password dengan invalid password', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        topbar.clickProfile()
        topbar.clickChangePSW()
        topbar.assertionChangePSW()
        topbar.inputValidData(FPLogin.invalidPSW, f04TopBar.newValidPSW)
        topbar.clickSave()
        topbar.assertionUnsuccessSavePSW()
    })
    it('Pengguna melakukan Change Password dengan valid password dan new password berupa karakter selain huruf dan angka', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        topbar.clickProfile()
        topbar.clickChangePSW()
        topbar.assertionChangePSW()
        topbar.inputValidData(FPLogin.invalidPSW, f04TopBar.newInvalidPSW)
        topbar.clickSave()
        topbar.assertionInvalidSavePSW()
    })
    it('Pengguna melakukan Change Password dengan valid password dan new password dengan confirm password berbeda', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        topbar.clickProfile()
        topbar.clickChangePSW()
        topbar.assertionChangePSW()
        topbar.inputBedaPSW(FPLogin.invalidPSW, f04TopBar.newValidPSW, f04TopBar.confirmPSW)
        topbar.clickSave()
        topbar.assertionBedaPSW()
    })
    it('Pengguna dapat mengakses fitur Log Out', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        topbar.clickProfile()
        topbar.clickLogOut()
        topbar.assertionLogOut()
    })
    it('Pengguna dapat mengakses fitur Upgrade', () => {
        loginPage.visitPage()
        loginPage.inputUSN(FPLogin.validUSN)
        loginPage.inputPSW(FPLogin.validPSW)
        loginPage.interceptSuccess()
        loginPage.clickLoginBTN()
        loginPage.waitSuccess()
        loginPage.assertionLogin()
        topbar.clickUpgrade()
        topbar.assertionUpgrade()
    })
})